language: node_js
before_script:
  - npm install
script:
- npm run build
deploy:
  provider: pages
  token: $GITHUB_TOKEN
  cleanup: false
  keep_history: false
  local_dir: public
  on:
    branch: master
